### ISSUE TITLE
Integrate `grammyjs/emoji` into the extension

### ISSUE THREAD

**Issue by Nazar-Ant** [grammyjs/vscode#6]
**Is your feature request related to a problem? Please describe.**
There's a great plugin for quickly searching for emojis without interrupting your code. This is useful when we write bot lines directly in the code. However, when a bot needs to be multilingual, we need to use emojis as usual, i.e. go to Telegram and search for them there and insert them into translated lines in `*.ftl` files.  

**Describe the solution you'd like**
I think it would be a great solution to integrate the tooltip provided by TypeScript into the extension. That is, the programmer starts typing `:gri` in the `en.ftl` file and the tooltip `:grinning_face: 😀` and similar options appear before him. 

Then you also need to develop a mechanism that would find and replace these emojis when translating `ctx.t()`.

**Describe alternatives you've considered**
Or you can do it even easier: when a user selects an emoji from a prompt, this emoji is immediately inserted into the text, so there's no need to parse anything. And when the user wants to change the emoji and presses `Backspace` to delete the character, the full name of the emoji will appear in its place, `:grinning_face:`, so that the user immediately recognizes the emoji ID and can conveniently change it to `:grinning_face_with_big_eyes:`, which will also immediately turn into an emoji.

**Additional context**
~~Add any other context or screenshots about the feature request here.~~

**Comment by Nazar-Ant** [comment]
I should add the label `Enhancement' here, but for some reason I can't do it

**Comment by Nazar-Ant** [comment]
By the way, if you implement the second option, you won't need the plugin at all, and working with emojis will be even more convenient.

**Comment by code-withAshish** [comment]
> Or you can do it even easier: when a user selects an emoji from a prompt, this emoji is immediately inserted into the text, so there's no need to parse anything. And when the user wants to change the emoji and presses Backspace to delete the character, the full name of the emoji will appear in its place, :grinning_face:, so that the user immediately recognizes the emoji ID and can conveniently change it to :grinning_face_with_big_eyes:, which will also immediately turn into an emoji.

you mean this `second method` ?

**Comment by Nazar-Ant** [comment]
@code-withAshish yes

**Comment by code-withAshish** [comment]
@Nazar-Ant i don't see how the extension wont be needed are you suggesting that we implement this in the core library of `grammy` itself ?

**Comment by Nazar-Ant** [comment]
@code-withAshish No, I'm saying that if you implement emoji search and substitution in the extension, the `grammyjs/emoji` plugin will not be needed, because its functionality will be implemented in the extension (and even in a better way).

This statement is true only for VS Code users, while users of other code editors and IDEs will not have such a great extension.

**Comment by code-withAshish** [comment]
@Nazar-Ant uhhh now I see what you are saying
Yeah it makes sense to integrate it in the extension itself.

> This statement is true only for VS Code users, while users of other code editors and IDEs will not have such a great extension.
agreed

**Comment by KnorpelSenf** [comment]
Inserting emoji into text files can be useful for all file types, and not just for bot projects. In fact, it is such a general idea that we may consider to either
1. add this feature to the extension for all file types in any context, or to
2. create a standalone extension that does this.

In either case we should check if no such extension exists already.

**Comment by code-withAshish** [comment]
> In either case we should check if no such extension exists already.

@KnorpelSenf  I checked on this and I did find some pretty good extensions that have already been developed such as 
[emojisense](https://marketplace.visualstudio.com/items?itemName=bierner.emojisense)

only thing that I dont have much idea about is the `names` of the emojis supported by this extension are fully compatible with telegram (I hope it does).

**Comment by KnorpelSenf** [comment]
Nice. It does not matter whether the names are compatible, given that the extension inserts the emoji directly as text.

**Comment by code-withAshish** [comment]
@KnorpelSenf 
Yup, i found out about this after this issue only

**Comment by KnorpelSenf** [comment]
@Nazar-Ant what else is left for this issue to be closed then, given that we can use existing extensions?

**Comment by Nazar-Ant** [comment]
The only thing is that this extension does not insert the emoji identifier in its place after deleting the emoji, so you can conveniently replace it with a similar one. In any case, this is not a very critical functionality.

**Comment by Nazar-Ant** [comment]
@KnorpelSenf This issue can be closed.

**Comment by KnorpelSenf** [comment]
Alright, nifty! More time to work on the other features of the extension 🎉
